### ISSUE TITLE
[Bug] Outdated structures cause DFU to process every time they are loaded

### ISSUE THREAD

**Issue by Linguardium** [Stardust-Labs-MC/Structory#10]
### What Minecraft version(s) does this apply to?

1.20

### Project version

1.3.4

### Mod or datapack version?

Mod (Fabric)

### Describe the bug

You have outdated structure files in your mod. This causes minecraft to try to update them every time they are loaded, leading to extra memory and cpu usage during worldgen. Please update your structures to match the mc version you are releasing for.

This should be as easy as loading them into game and re-saving them or using a mod to load them into a StructureTemplate and writing them back out to nbt.

I understand datapacks are released for wider ranges of minecraft, but structures shoulds till be updated to the minimum version within that range.

**Comment by catter1** [comment]
This will likely not happen. Due to some tests by some others, the startup time impact is measured in milliseconds. It's negligible.
