### ISSUE TITLE
[Bug] Incorrect/Missing loot table in structures/harvest/manor2/zombie.nbt

### ISSUE THREAD

**Issue by Linguardium** [Stardust-Labs-MC/Structory#11]
### What Minecraft version(s) does this apply to?

1.20

### Project version

https://github.com/Stardust-Labs-MC/Structory/commit/7571e8998ee5ecd62b5ae8095b8155b0c627a2e7

### Mod or datapack version?

Datapack

### Describe the bug

Barrel in `structures/harvest/manor2/zombie.nbt` references loot table `structory:outcast/ruin/low` which does not exist.

### Additional context

N/A

**Comment by catter1** [comment]
Fixed in 1.3.5
