### ISSUE TITLE
[Bug] Couldn't read tag list "structory:has_structure/outcast_villager_desert

### ISSUE THREAD

**Issue by cr-gomezm** [Stardust-Labs-MC/Structory#15]
### What Minecraft version(s) does this apply to?

1.21 - 1.21.1, 1.21.2 - 1.21.3

### Project version

1.3.8 w/ towers_1.0.10

### Mod or datapack version?

Fabric/Quilt Mod

### Describe the bug

After updating to 1.3.8 this error is dumped into de console during start:

[Worker-Main-26/ERROR]: Couldn't read tag list structory:has_structure/outcast_villager_desert from structory:tags/worldgen/biome/has_structure/outcast_villager_desert.json in data pack structory
java.lang.IllegalStateException: Failed to parse either. First: Not a string: null; Second: Not a JSON object: null

This happens on my 1.21 servers and on the updated ones to 1.21.3.... fabric launcher  0.16.9

**Comment by catter1** [comment]
Fixed in [1.3.9](https://modrinth.com/datapack/structory/version/1.3.9)

**Comment by nacklebert** [comment]
Still persists in the Datapack version
